### ISSUE TITLE
Answers don't seem to be sending properly

### ISSUE THREAD

**Issue by ZachC16** [lorpus/pyhq#8]
I'm playing the game over a websocket connection and sending answers as follows: 

    print(websocket.send_json(json.dumps({"answerId":answerId,
                                                 "questionId":message_data["questionId"],
                                                 "broadcastId":broadcastId,
                                                "authToken":bearer,
                                                 "type": "answer"})))

When I print this, "None" is printed to the console (it didn't work when I didn't print either). The "questionSummary" type response I get confirms that I'm not getting the question right even when I send the correct answer:

    "youGotItRight:"False"
    "yourAnswerId":-1

So no answer is getting through. How do I fix this?

**Comment by vocabexpresshaxer** [comment]
Same problem

**Comment by vocabexpresshaxer** [comment]
Ok, so i've managed to get some data, although some of it needs to be decode / im not really too sure. hopefully someone can make sense of this

https://pastebin.com/wRA2uUX1
https://pastebin.com/syrekEzP

**Comment by lorpus** [comment]
1st paste just looks encoded/compressed, don't think it matters though

still seems to work for some people i've been talking to for a while, no changes. not sure why it's not working for you anymore but here's what i can suggest trying

* remove authToken param because it's unnecessary
* make sure the parameters are in the right order (not sure if this is necessary but worth a shot)
* make sure the types are right (int instead of string)

**Comment by vocabexpresshaxer** [comment]
@lorpus you can close this issue - it was down to me

**Comment by ZachC16** [comment]
>@lorpus you can close this issue - it was down to me

@vocabexpresshaxer Did you fix this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
